### ISSUE TITLE
when will the Act 3 save file update release?

### ISSUE THREAD

**Issue by rom0119** [PyPylia/ultrakill-save-editor#11]
I've once opened an issue where i asked about an error,and you,the creator,responded like this:

"The issue with it instantly closing is due to a change in the save data format in the latest update. I am actively working on fixing this."

Since that message,it has been 2 weeks,and yet,it still closes and the update isn't out,which bothers me alot,so i ask you a favor to tell me,when will it release? (not exact date only)
![Скриншот 12-01-2024 201835](https://github.com/PyPylia/ultrakill-save-editor/assets/155007669/873f7900-4ffa-4929-8473-d58057f4b209)
Thanks.

**Comment by PyPylia** [comment]
Merged into #13
