### ISSUE TITLE
Cant Find The App

### ISSUE THREAD

**Issue by CaelUs2** [PyPylia/ultrakill-save-editor#16]
When i extract , either on Winrar or 7zip , i cant find the app, i have extracted it both with my antivirus on and off to see if it was detected as a virus perhaps , any possible solution?
Thanks in advance.

**Comment by PyPylia** [comment]
Please download the executable file from the [releases](https://github.com/PyPylia/ultrakill-save-editor/releases) page. The zip/tar.gz files either from the "Code" button on the main page, or the "Source code" options in the releases merely downloads the source code. This means you'd have to recompile the app yourself, which you can do, but requires installing the rust language.
