### ISSUE TITLE
wont open

### ISSUE THREAD

**Issue by Clyv1** [PyPylia/ultrakill-save-editor#19]
ive tried all the versions but it just opens and almost instantly closes, idk what to do

**Comment by Ultramatteo22** [comment]
the same thing happens to me, I can't open it, it just immediately closes.
I been waiting for a fix, none of the versions let me open it.

**Comment by TheCourpseOfKingUltraKillModder** [comment]
same

**Comment by PyPylia** [comment]
This is likely a duplicate of #13 unless you are running this on an older version that is supported. If so, please re-open this issue.
