### ISSUE TITLE
where do i download it

### ISSUE THREAD

**Issue by Existencers** [PyPylia/ultrakill-save-editor#21]
where do i download the app i cant find it I'm new to github so I'm pretty clueless

**Comment by ydrk** [comment]
click the releases button bro...

**Comment by TheCourpseOfKingUltraKillModder** [comment]
THERE IS NO FUCKING RELEASES BUTTON YDRK.USE YOUR FUCKING EYES DUMBASS.

**Comment by ydrk** [comment]
> THERE IS NO FUCKING RELEASES BUTTON YDRK.USE YOUR FUCKING EYES DUMBASS.

![image](https://github.com/user-attachments/assets/4dd87a6b-9b4d-4e38-a731-72451c3d122c)
![image](https://github.com/user-attachments/assets/fff95c81-aef1-4e45-bfa6-87ce22e94b59)

u good homie?
