### ISSUE TITLE
the app wont open

### ISSUE THREAD

**Issue by Cesar5156** [PyPylia/ultrakill-save-editor#7]
When I allow it to run after the smartscreen popup, it just crashes. When I unistalled ultrakill, the problem disappeared, but when i tried to load up my backup of my save files, it crashes, so its a problem around directories.

**Comment by rom0119** [comment]
i already asked that question and he said something like 

"The issue with it instantly closing is due to a change in the save data format in the latest update. I am actively working on fixing this."

i think this is our problem

**Comment by caffienate** [comment]
I think that was an issue with windows defender, mine just cant handle directiories.

**Comment by PillowQueso** [comment]
it's a issue with file directory, put you ultrakill file into the steam file

**Comment by rom0119** [comment]
the ultrakill file is litteraly in the steam folder all the time,wdym
(sorry if i didn't understand you)

**Comment by Cesar5156** [comment]
anytime it tries to read a .bepis file(i presume), it crashes, no matter where it is

**Comment by mikeyaeaeae** [comment]
how do i fix? got the same problem when i hit "load"

**Comment by Cesar5156** [comment]
i presume its that "new" save format that came with violence update i read back a few comments in this thread

**Comment by thedexterbear** [comment]
it was working for me yesterday, i tried using it again today and i'm now having this issue

**Comment by PyPylia** [comment]
Merged into #13
